import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import './globals.css';
import { AuthProvider } from './Providers';

const inter = Inter({
	subsets: ['latin'],
});

export const metadata = {
	title: 'Visit Gulu',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${inter.className} scroll-smooth antialiased`}>
			<body className='flex flex-col min-h-screen'>
				<Navbar />
				<main className='flex-grow w-full mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'>
					<div className='container mx-auto'>
						<AuthProvider>{children}</AuthProvider>
					</div>
				</main>
				<Footer />
			</body>
		</html>
	);
}
