import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import './globals.css';

const inter = Inter({
	subsets: ['latin'],
});

export const metadata = {
	title: 'Visit Gulu',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				<main className='mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8'>
					{children}
        </main>
        <Footer />
			</body>
		</html>
	);
}
